

class Format:
    DATE_FORMAT = "%Y-%m-%dT%H:%M:%S+05:30"
    DATE_FORMAT_WITH_TIME = "%Y-%m-%d %H:%M:%S"
    DATE_FORMAT_WITH_TIME_WITH_TZ = "%Y-%m-%d %H:%M:%S+05:30"
    DATE_FORMAT_WITH_TIME_WITH_TZ_WITH_MS = "%Y-%m-%d %H:%M:%S.%f+05:30"
    DATE_FORMAT_WITH_TIME_WITH_TZ_WITH_MS_WITH_TZ = "%Y-%m-%d %H:%M:%S.%f+05:30"
    DATE_FORMAT_WITH_TIME_WITH_TZ_WITH_MS_WITH_TZ_WITH_MS = "%Y-%m-%d %H:%M:%S.%f+05:30"
    DATE_FORMAT_WITH_TIME_WITH_TZ_WITH_MS_WITH_TZ_WITH_MS_WITH_MS = "%Y-%m-%d %H:%M:%S.%f+05:30"
    DATE_FORMAT_WITH_TIME_WITH_TZ_WITH_MS_WITH_TZ_WITH_MS_WITH_MS_WITH_MS = "%Y-%m-%d %H:%M:%S.%f+05:30"
    BASIC_DATE_FORMAT = "%Y-%m-%d"